; 写真アップロード（1枚10MB × 10枚まで）
upload_max_filesize = 12M
post_max_size = 128M
memory_limit = 512M
max_execution_time = 180
expose_php = Off
date.timezone = Asia/Tokyo

opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
